language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

install:
  - ./pkg-build.sh install_github jimhester/covr
  - ./pkg-build.sh install_bioc BiocCheck
  - ./pkg-build.sh install_bioc DESeq
  - ./pkg-build.sh install_bioc DESeq2
  - ./pkg-build.sh install_bioc airway
  - ./pkg-build.sh install_bioc_deps

script:
  - ./pkg-build.sh run_tests

after_script:
  - ./pkg-build.sh run_script -e 'covr::codecov()'
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - ./pkg-build.sh run_script -e "library(BiocCheck); BiocCheck(\"${FILE}\")"


notifications:
  email:
    on_success: change
    on_failure: always

env:
  - RVERSION=devel