language: r
sudo: false
cache: packages

r:
  - devel
warnings_are_errors: false
bioc_required: true
bioc_use_devel: true

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: always
