---
title: "out_of_bag"
format: html
editor: visual
---

## Quarto

parameters

```{r}
m <- 1000
nfolds <- 4
ntrees_all_comb <- 1 #single tree in forest
```

```{r}
#pvalues <- runif(m)
folds <- sample(seq_len(nfolds), m, replace = TRUE)
```

Let's fix a fold `i = 3` and assume a random forest with a single tree `t = 1`

```{r}
i <- 3
inbag_matrices_i <- sample(c(0,1), sum(folds!=i)*ntrees_all_comb, replace = TRUE, prob = c(0.2, 0.8))
inbag_matrices_i <- matrix(inbag_matrices_i, ncol = ntrees_all_comb)
```

```{r}
completed_inbag_matrix <- 
      matrix(rep(2, m*ntrees_all_comb), nrow = m, ncol = ntrees_all_comb)
    
completed_inbag_matrix[folds != i, ] <- inbag_matrices_i
```

```{r}
#1 = out of fold, in.bag, 0 = out of fold, out.of.bag, 2 = in hold out fold
table(completed_inbag_matrix)
```

| Encoding | Interpretation          | Usage                              |
|----------|-------------------------|------------------------------------|
| 1        | out of fold, in.bag     | used for construction of partition |
| 0        | out of fold, out.of.bag | used for construction of weights   |
| 2        | in hold out fold        | P value used for decision rule     |
