---
title: "test_forest"
format: html
editor: visual
---

## Quarto

```{r, echo = FALSE, message = FALSE, warning=FALSE}
devtools::load_all()
```

```{r, eval=FALSE}
 #save.seed <- .Random.seed
 set.seed(1)
 X <- runif(20000, min = 0, max = 2.5) # covariate
 H <- rbinom(20000, 1, 0.1) # hypothesis true or false
 Z <- rnorm(20000, H * X) # Z-score
 folds <- sample(1:5, 20000, replace = TRUE)
#' .Random.seed <- save.seed
pvalue <- 1 - pnorm(Z) # pvalue
groups_inbag_matrices <- group_by_forest(pvalue, as.matrix(X), folds)
```

```{r, eval=FALSE}
groups <- groups_inbag_matrices$groups
inbag_matrices <- groups_inbag_matrices$inbag_matrices
```

```{r}

```

```{r}
 X   <- runif(20000, min=0, max=2.5)   # covariate
 H   <- rbinom(20000,1,0.1)            # hypothesis true or false
 Z   <- rnorm(20000, H*X)              # Z-score
#' .Random.seed <- save.seed
 pvalue <- 1-pnorm(Z)                  # pvalue
#'
 ihw_fdr <- ihw(pvalue, X, .1, stratification_method = "forest")  
```

Challanges:

-   sorting

-   complete to out-of-fold

```{r}
m <- 10
i <- 2
ntrees_all_comb <- 5
pvalues <- runif(m)
folds <- sample(c(1,2,3,4), m, replace = TRUE)
inbag_matrices_i <- sample(c(0,1), sum(folds==i)*ntrees_all_comb, replace = TRUE)
inbag_matrices_i <- matrix(inbag_matrices_i, ncol = ntrees_all_comb)
```

```{r}
order_pvalues <- order(pvalues)

completed_inbag_matrix <- 
matrix(rep(2, m*ntrees_all_comb), nrow = m, ncol = ntrees_all_comb)

completed_inbag_matrix[folds == i, ] <- inbag_matrices_i
sorted_completed_inbag_matrix <- completed_inbag_matrix[order_pvalues, , drop = FALSE]
```
